# Generated by Django 5.2.4 on 2025-07-20 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMBCChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusting_tube', models.CharField(choices=[('Good', 'Good'), ('Cracked', 'Cracked'), ('Worn Out', 'Worn Out'), ('Damaged', 'Damaged'), ('Other', 'Other')], max_length=50)),
                ('cylinder_body', models.CharField(choices=[('Good', 'Good'), ('Cracked', 'Cracked'), ('Worn Out', 'Worn Out'), ('Damaged', 'Damaged'), ('Other', 'Other')], max_length=50)),
                ('piston_trunnion', models.CharField(choices=[('Good', 'Good'), ('Cracked', 'Cracked'), ('Worn Out', 'Worn Out'), ('Damaged', 'Damaged'), ('Other', 'Other')], max_length=50)),
                ('plunger_spring', models.CharField(choices=[('Good', 'Good'), ('Cracked', 'Cracked'), ('Worn Out', 'Worn Out'), ('Damaged', 'Damaged'), ('Other', 'Other')], max_length=50)),
                ('tee_bolt', models.CharField(choices=[('Good', 'Good'), ('Cracked', 'Cracked'), ('Worn Out', 'Worn Out'), ('Damaged', 'Damaged'), ('Other', 'Other')], max_length=50)),
                ('pawl', models.CharField(choices=[('Good', 'Good'), ('Cracked', 'Cracked'), ('Worn Out', 'Worn Out'), ('Damaged', 'Damaged'), ('Other', 'Other')], max_length=50)),
                ('pawl_spring', models.CharField(choices=[('Good', 'Good'), ('Cracked', 'Cracked'), ('Worn Out', 'Worn Out'), ('Damaged', 'Damaged'), ('Other', 'Other')], max_length=50)),
                ('dust_excluder', models.CharField(choices=[('Good', 'Good'), ('Cracked', 'Cracked'), ('Worn Out', 'Worn Out'), ('Damaged', 'Damaged'), ('Other', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BogieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogie_no', models.CharField(max_length=100)),
                ('maker_year_built', models.CharField(max_length=100)),
                ('incoming_div_and_date', models.CharField(max_length=100)),
                ('deficit_components', models.TextField(blank=True)),
                ('date_of_ioh', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axile_guide_assembly', models.CharField(choices=[('Good', 'Good'), ('Worn', 'Worn'), ('Misalign', 'Misalign'), ('Other', 'Other')], max_length=50)),
                ('axle_guide', models.CharField(choices=[('Good', 'Good'), ('Worn', 'Worn'), ('Misalign', 'Misalign'), ('Other', 'Other')], max_length=50)),
                ('bogieFrameCondition', models.CharField(choices=[('Good', 'Good'), ('Cracked', 'Cracked'), ('Worn Out', 'Worn Out'), ('Damaged', 'Damaged'), ('Other', 'Other')], max_length=100)),
                ('bolster', models.CharField(choices=[('Good', 'Good'), ('Cracked', 'Cracked'), ('Worn Out', 'Worn Out'), ('Bent', 'Bent'), ('Other', 'Other')], max_length=50)),
                ('bolster_suspension_bracket', models.CharField(choices=[('Good', 'Good'), ('Cracked', 'Cracked'), ('Corroded', 'Corroded'), ('Other', 'Other')], max_length=50)),
                ('lower_spring_seat', models.CharField(choices=[('Good', 'Good'), ('Cracked', 'Cracked'), ('Worn Out', 'Worn Out'), ('Damaged', 'Damaged'), ('Other', 'Other')], max_length=50)),
                ('protective_tubes', models.CharField(choices=[('Good', 'Good'), ('Cracked', 'Cracked'), ('Worn Out', 'Worn Out'), ('Damaged', 'Damaged'), ('Other', 'Other')], max_length=50)),
                ('anchor_links', models.CharField(choices=[('Good', 'Good'), ('Cracked', 'Cracked'), ('Worn Out', 'Worn Out'), ('Damaged', 'Damaged'), ('Other', 'Other')], max_length=50)),
                ('side_bearer', models.CharField(choices=[('Good', 'Good'), ('Cracked', 'Cracked'), ('Worn Out', 'Worn Out'), ('Damaged', 'Damaged'), ('Other', 'Other')], max_length=50)),
                ('bogie_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bogie_checksheet.bogiedetails')),
            ],
        ),
        migrations.CreateModel(
            name='BogieFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=100, unique=True)),
                ('inspection_by', models.CharField(max_length=100)),
                ('inspection_date', models.DateField()),
                ('bmbc_checksheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bogie_checksheet.bmbcchecksheet')),
                ('bogie_checksheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bogie_checksheet.bogiechecksheet')),
            ],
        ),
    ]
